name: CI tests
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:
  contents: read

# Cannot run tests on windows and mac because of docker
# See https://github.com/orgs/community/discussions/25777
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        run: make test
